version: '3'

services:
  nginx:
    build:
      context: ./ui
      dockerfile: Dockerfile-Paperless-UI
    container_name: paperless-ui
    ports:
      - "80:80"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile-Paperless-API
    container_name: paperless-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  postgres:
    image: postgres:latest
    container_name: paperless-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_DB=paperless
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "paperless"]
      interval: 10s
      timeout: 5s
      retries: 20
