FROM openjdk:19-alpine

# Working directory in the container
WORKDIR /app

# We copy the entire app
COPY src /app/src/
COPY pom.xml /app/pom.xml
COPY mvnw /app/mvnw
COPY .mvn /app/.mvn/

# Build the jar file
RUN ./mvnw package

# Expose port 8080
EXPOSE 8080

# Run the jar file
CMD ["java", "-jar", "target/paperless-1.0.jar"]